package ui.theme
import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF6750A4)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFEADDFF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF21005D)
internal val md_theme_light_secondary = Color(0xFF625B71)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFE8DEF8)
internal val md_theme_light_onSecondaryContainer = Color(0xFF1D192B)
internal val md_theme_light_tertiary = Color(0xFF7D5260)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFFFD8E4)
internal val md_theme_light_onTertiaryContainer = Color(0xFF31111D)
internal val md_theme_light_error = Color(0xFFB3261E)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_errorContainer = Color(0xFFF9DEDC)
internal val md_theme_light_onErrorContainer = Color(0xFF410E0B)
internal val md_theme_light_outline = Color(0xFF79747E)
internal val md_theme_light_background = Color(0xFFFFFBFE)
internal val md_theme_light_onBackground = Color(0xFF1C1B1F)
internal val md_theme_light_surface = Color(0xFFFFFBFE)
internal val md_theme_light_onSurface = Color(0xFF1C1B1F)
internal val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
internal val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
internal val md_theme_light_inverseSurface = Color(0xFF313033)
internal val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
internal val md_theme_light_inversePrimary = Color(0xFFD0BCFF)
internal val md_theme_light_surfaceTint = Color(0xFF6750A4)
internal val md_theme_light_outlineVariant = Color(0xFFCAC4D0)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFFD0BCFF)
internal val md_theme_dark_onPrimary = Color(0xFF381E72)
internal val md_theme_dark_primaryContainer = Color(0xFF4F378B)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF)
internal val md_theme_dark_secondary = Color(0xFFCCC2DC)
internal val md_theme_dark_onSecondary = Color(0xFF332D41)
internal val md_theme_dark_secondaryContainer = Color(0xFF4A4458)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8)
internal val md_theme_dark_tertiary = Color(0xFFEFB8C8)
internal val md_theme_dark_onTertiary = Color(0xFF492532)
internal val md_theme_dark_tertiaryContainer = Color(0xFF633B48)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8E4)
internal val md_theme_dark_error = Color(0xFFF2B8B5)
internal val md_theme_dark_onError = Color(0xFF601410)
internal val md_theme_dark_errorContainer = Color(0xFF8C1D18)
internal val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
internal val md_theme_dark_outline = Color(0xFF938F99)
internal val md_theme_dark_background = Color(0xFF1C1B1F)
internal val md_theme_dark_onBackground = Color(0xFFE6E1E5)
internal val md_theme_dark_surface = Color(0xFF1C1B1F)
internal val md_theme_dark_onSurface = Color(0xFFE6E1E5)
internal val md_theme_dark_surfaceVariant = Color(0xFF49454F)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
internal val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
internal val md_theme_dark_inverseOnSurface = Color(0xFF313033)
internal val md_theme_dark_inversePrimary = Color(0xFF6750A4)
internal val md_theme_dark_surfaceTint = Color(0xFFD0BCFF)
internal val md_theme_dark_outlineVariant = Color(0xFF49454F)
internal val md_theme_dark_scrim = Color(0xFF000000)


internal val seed = Color(0xFF6750A4)
